-- MySQL Script generated by MySQL Workbench
-- Wed Nov  7 11:09:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fastorder
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fastorder` ;

-- -----------------------------------------------------
-- Schema fastorder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fastorder` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fastorder` ;

-- -----------------------------------------------------
-- Table `fastorder`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastorder`.`store` ;

CREATE TABLE IF NOT EXISTS `fastorder`.`store` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `StoreKey` VARCHAR(200) NOT NULL,
  `Location` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `StoreName` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `PhoneNumber` VARCHAR(50) NULL DEFAULT NULL,
  `Province` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `UserId` INT(11) NULL DEFAULT NULL,
  `IsDeleted` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastorder`.`table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastorder`.`table` ;

CREATE TABLE IF NOT EXISTS `fastorder`.`table` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `TableKey` VARCHAR(200) NOT NULL,
  `StoreId` INT(11) NOT NULL,
  `TableName` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `IsAvailable` BIT(1) NOT NULL DEFAULT b'1',
  `IsDeleted` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`Id`),
  INDEX `fk_table_store1_idx` (`StoreId` ASC) VISIBLE,
  CONSTRAINT `fk_table_store1`
    FOREIGN KEY (`StoreId`)
    REFERENCES `fastorder`.`store` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastorder`.`bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastorder`.`bill` ;

CREATE TABLE IF NOT EXISTS `fastorder`.`bill` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `TableId` INT(11) NULL DEFAULT NULL,
  `DateCreate` DATETIME NULL DEFAULT NULL,
  `Total` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_bill_table1_idx` (`TableId` ASC) VISIBLE,
  CONSTRAINT `fk_bill_table1`
    FOREIGN KEY (`TableId`)
    REFERENCES `fastorder`.`table` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
DELAY_KEY_WRITE = 1;


-- -----------------------------------------------------
-- Table `fastorder`.`billdetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastorder`.`billdetail` ;

CREATE TABLE IF NOT EXISTS `fastorder`.`billdetail` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `BillId` INT(11) NULL DEFAULT NULL,
  `ProductId` INT(11) NULL DEFAULT NULL,
  `ProductName` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Quantity` INT(11) NULL DEFAULT NULL,
  `Price` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_billdetail_bill1_idx` (`BillId` ASC) VISIBLE,
  CONSTRAINT `fk_billdetail_bill1`
    FOREIGN KEY (`BillId`)
    REFERENCES `fastorder`.`bill` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastorder`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastorder`.`image` ;

CREATE TABLE IF NOT EXISTS `fastorder`.`image` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `ImgKey` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `DateCreate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastorder`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastorder`.`order` ;

CREATE TABLE IF NOT EXISTS `fastorder`.`order` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `TableId` INT(11) NULL DEFAULT NULL,
  `DateCreate` DATETIME NULL DEFAULT NULL,
  `Total` FLOAT NULL DEFAULT NULL,
  `Status` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_order_table1_idx` (`TableId` ASC) VISIBLE,
  CONSTRAINT `fk_order_table1`
    FOREIGN KEY (`TableId`)
    REFERENCES `fastorder`.`table` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastorder`.`orderdetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastorder`.`orderdetail` ;

CREATE TABLE IF NOT EXISTS `fastorder`.`orderdetail` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `OrderId` INT(11) NULL DEFAULT NULL,
  `ProductId` INT(11) NULL DEFAULT NULL,
  `ProductName` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Quantity` INT(11) NULL DEFAULT NULL,
  `Price` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_orderdetail_order_idx` (`OrderId` ASC) VISIBLE,
  CONSTRAINT `fk_orderdetail_order`
    FOREIGN KEY (`OrderId`)
    REFERENCES `fastorder`.`order` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastorder`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastorder`.`type` ;

CREATE TABLE IF NOT EXISTS `fastorder`.`type` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastorder`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastorder`.`products` ;

CREATE TABLE IF NOT EXISTS `fastorder`.`products` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `StoreId` INT(11) NULL DEFAULT NULL,
  `ImageId` INT(11) NULL DEFAULT NULL,
  `ProductName` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ProductPrice` FLOAT NULL DEFAULT NULL,
  `TypeId` INT(11) NULL DEFAULT NULL,
  `IsDeleted` BIT(1) NULL DEFAULT b'0',
  `IsAvailable` BIT(1) NULL DEFAULT b'1',
  PRIMARY KEY (`Id`),
  INDEX `fk_products_store1_idx` (`StoreId` ASC) VISIBLE,
  INDEX `fk_products_image1_idx` (`ImageId` ASC) VISIBLE,
  INDEX `fk_products_type1_idx` (`TypeId` ASC) VISIBLE,
  CONSTRAINT `fk_products_image1`
    FOREIGN KEY (`ImageId`)
    REFERENCES `fastorder`.`image` (`Id`),
  CONSTRAINT `fk_products_store1`
    FOREIGN KEY (`StoreId`)
    REFERENCES `fastorder`.`store` (`Id`),
  CONSTRAINT `fk_products_type1`
    FOREIGN KEY (`TypeId`)
    REFERENCES `fastorder`.`type` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastorder`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastorder`.`role` ;

CREATE TABLE IF NOT EXISTS `fastorder`.`role` (
  `Id` INT(11) NOT NULL,
  `RoleType` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastorder`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastorder`.`user` ;

CREATE TABLE IF NOT EXISTS `fastorder`.`user` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(32) NOT NULL,
  `Fullname` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `Address` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `StoreId` INT(11) NULL DEFAULT NULL,
  `RoleId` INT(11) NOT NULL,
  `Password` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL,
  `IsDeleted` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`Id`),
  INDEX `fk_user_role1_idx` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`RoleId`)
    REFERENCES `fastorder`.`role` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `fastorder` ;

-- -----------------------------------------------------
-- procedure AddNewProduct
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`AddNewProduct`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddNewProduct`(
	_StoreId int,
	_ImgUrl text,
	_ProductName text,
    _ProductPrice float,
    _TypeId int
)
BEGIN
	DECLARE _Curdate datetime DEFAULT current_time();
    
	INSERT INTO `fastorder`.`image` (`ImgKey`, `DateCreate`) VALUES (
	_ImgUrl, _Curdate
	);
    
    INSERT INTO `fastorder`.`products` (`StoreId`, `ImageId`, `ProductName`, `ProductPrice`, `TypeId`) VALUES (
    _StoreId,
    (select id from image where ImgKey LIKE _ImgUrl and DateCreate = _Curdate),
    _ProductName,
    _ProductPrice,
    _TypeId
	);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure AddNewStore
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`AddNewStore`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddNewStore`(
	_StoreName text,
    _PhoneNumber text,
    _Location text,
    _Province text
)
BEGIN
	INSERT INTO fastorder.`store` (StoreKey,`Location`, StoreName, PhoneNumber, Province) VALUES
	(
    '', _Location, _StoreName, _PhoneNumber, _Province
    );

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure AddNewTable
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`AddNewTable`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddNewTable`(
    _StoreId int,
	_TableKey text,
    _TableName text
)
BEGIN
	INSERT INTO fastorder.`table`( TableKey, StoreId, TableName) VALUES
	(
    _TableKey, _StoreId, _TableName
    );

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure AddToBillDetail
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`AddToBillDetail`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddToBillDetail`(
    IN _BillId int,
    IN _ProductId int,
    IN _Quantity int
)
BEGIN
	INSERT INTO `fastorder`.`billdetail`(`BillId`,`ProductId`,`ProductName`,`Quantity`,`Price`)VALUES
	(	_BillId,
		_ProductId,
	(select ProductName from products where id = _ProductId),
		_Quantity,
	(select ProductPrice from products where id = _ProductId) * _Quantity
	);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure AddToOrderDetail
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`AddToOrderDetail`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddToOrderDetail`(
    IN _OrderId int,
    IN _ProductId int,
    IN _Quantity int
)
BEGIN
	INSERT INTO `fastorder`.`orderdetail`(`OrderId`,`ProductId`,`ProductName`,`Quantity`,`Price`)VALUES
	(	_OrderId,
		_ProductId,
	(select ProductName from products where id = _ProductId),
		_Quantity,
	(select ProductPrice from products where id = _ProductId) * _Quantity
	);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CreateNewBill
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`CreateNewBill`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `CreateNewBill`(
	_TableKey text
)
BEGIN
	DECLARE _Curdate datetime DEFAULT current_time();
	DECLARE _TableId int DEFAULT (select id from `table` where TableKey = _TableKey);
    
	INSERT INTO `fastorder`.`bill` (`TableId`,`DateCreate`)VALUES
	((select id from `table` where tablekey = _TableKey),
		_Curdate
    );
    
    select id as billId from bill where TableId=_TableId and DateCreate=_Curdate;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CreateNewBillRaft
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`CreateNewBillRaft`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `CreateNewBillRaft`(
	_TableKey text,
    _ProductId int,
    _Quantity int
)
BEGIN
	DECLARE _Curdate datetime DEFAULT current_time();
	DECLARE _TableId int DEFAULT (select id from `table` where TableKey = _TableKey);
    
	INSERT INTO `fastorder`.`bill` (`TableId`,`DateCreate`)VALUES
	((select id from `table` where tablekey = _TableKey),
		_Curdate
    );
    INSERT INTO `fastorder`.`billdetail`(`BillId`,`ProductId`,`ProductName`,`Quantity`,`Price`)VALUES
	((select id from bill where TableId=_TableId and DateCreate=_Curdate),
		_ProductId,
	 (select ProductName from products where id = _ProductId),
		_Quantity,
	 (select ProductPrice from products where id = _ProductId)
	);


END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CreateNewOrder
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`CreateNewOrder`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `CreateNewOrder`(
	_TableKey text
)
BEGIN
	DECLARE _Curdate datetime DEFAULT current_time();
	DECLARE _TableId int DEFAULT (select id from `table` where TableKey = _TableKey);
    
	INSERT INTO `fastorder`.`order` (`TableId`,`DateCreate`)VALUES
	((select id from `table` where tablekey = _TableKey),
		_Curdate
    );
    
    select id as orderId from `order` where TableId=_TableId and DateCreate=_Curdate;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure GetBillByStoreId
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`GetBillByStoreId`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetBillByStoreId`(
	_StoreId int
)
BEGIN
	SELECT 
		b.Id,
		b.TableId,
		t.TableName,
		b.DateCreate,
    (SELECT SUM(price) AS Total FROM billdetail bd 
		WHERE bd.billid = b.Id) AS Total
FROM
    `bill` b
        JOIN
    `table` t ON t.Id = b.TableId
        JOIN
    store s ON s.Id = t.StoreId
WHERE
    s.Id = _StoreId
;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure GetOrderByStoreId
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`GetOrderByStoreId`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetOrderByStoreId`(
	_StoreId int
)
BEGIN
	SELECT 
    s.Id AS StoreId,
    t.Id AS TableId,
    o.Id AS OrderId,
    o.DateCreate,
    (SELECT SUM(price) AS Total FROM orderdetail od
                WHERE od.orderid = o.Id) AS Total,
    CASE WHEN o.Status = 0 THEN FALSE ELSE TRUE END AS `Status`
	FROM
		`order` o
			JOIN
		`table` t ON t.Id = o.TableId
			JOIN
		store s ON s.Id = t.StoreId
	WHERE
		s.Id = _StoreId
     order by o.Id  desc
	;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure GetProductByStoreId
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`GetProductByStoreId`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetProductByStoreId`(
	_StoreId int
)
BEGIN
	SELECT 
		s.Id AS StoreId,
		p.Id AS ProductId,
		im.ImgKey,
		p.ProductName,
		p.ProductPrice,
        CASE WHEN p.IsAvailable = 1 THEN TRUE ELSE FALSE END AS IsAvailable,
        p.TypeId,
        t.Type
        
	FROM
		`products` p
		JOIN store s ON s.Id = p.StoreId
		JOIN image im ON im.id = p.imageid
        JOIN type t ON t.Id = p.TypeID
	WHERE
		s.Id = _StoreId AND p.IsDeleted = 0
	;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure TableGetTableByStoreId
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`TableGetTableByStoreId`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `TableGetTableByStoreId`(
	_StoreId int
)
BEGIN
	SELECT 	t.Id AS TableId,
			s.Id AS StoreId,
            t.TableKey,
            t.TableName,
            s.StoreName, 
            CASE WHEN t.IsAvailable = 1 THEN TRUE ELSE FALSE END AS IsAvailable
            FROM `table` t
            JOIN store s ON s.Id = t.StoreId
            WHERE t.StoreId = _StoreId and t.IsDeleted = 0
	;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UpdateProduct
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`UpdateProduct`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UpdateProduct`(
	_ProductId int,
    _ImgUrl text,
    _ProductName text,
    _ProductPrice int,
    _IsAvailable int,
    _TypeId int
)
BEGIN

	DECLARE _Curdate datetime DEFAULT current_time();
    
	UPDATE `fastorder`.`products` SET 
    `ProductName` 	= _ProductName,
	`ProductPrice` 	= _ProductPrice,
	`IsAvailable` 	= _IsAvailable,
    `TypeId` 		= _TypeId
	WHERE `Id` = _ProductId;
    
    UPDATE `fastorder`.`image` SET
		`ImgKey` = _ImgUrl,
		`DateCreate` = _Curdate
	WHERE `Id` = (select ImageId from products where id = _ProductId);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure addUser
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`addUser`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `addUser`(
	_UserName text,
    _Fullname text,
    _Address text,
    _StoreId int,
    _RoleId int,
    _Password text
)
BEGIN
	INSERT INTO `fastorder`.`user` (`UserName`, `Fullname`, `Address`, `StoreId`, `RoleId`, `Password`) VALUES
(_UserName,  _Fullname,_Address, _StoreId ,  _RoleId , _Password)
;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure checkLogin
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`checkLogin`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `checkLogin`(
	In _Username text,
    In _Password text
)
BEGIN

	SELECT 
		u.Id As UserId, r.Id As RoleId, s.Id As StoreId, 
		u.UserName, u.Fullname, s.StoreName, r.RoleType
	FROM 
		`user` u
		JOIn `role`r ON r.Id = u.RoleId 
		join store s on s.Id = u.StoreId
	where 
		u.UserName = _Username
		
	 and u.Password = _Password
	 ;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure getRoleAndStoreId
-- -----------------------------------------------------

USE `fastorder`;
DROP procedure IF EXISTS `fastorder`.`getRoleAndStoreId`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `getRoleAndStoreId`(
	In _Username text,
    In _Password text
)
BEGIN

	SELECT 
		u.Id As UserId, r.Id As RoleId, s.Id As StoreId,
		u.UserName, u.Fullname, s.StoreName, r.RoleType,
		CASE WHEN s.IsDeleted = 0 THEN FALSE ELSE TRUE END AS IsDeleted
	FROM 
		`user` u
		JOIn `role`r ON r.Id = u.RoleId 
		join store s on s.Id = u.StoreId
	where 
		u.UserName like _Username
		
	 and u.Password like _Password
	 ;

END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE `fastorder`;
DROP procedure IF EXISTS `GetOrderDetailByOrderId`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetOrderDetailByOrderId`(
	_OrderId int
)
BEGIN
	SELECT 	od.OrderId, 
            t.TableName,
            od.ProductName,
            od.Quantity,
            od.Price,
            o.DateCreate
	FROM
		orderdetail od
		JOIN `order` o ON od.OrderId = o.Id
		JOIN `table` t ON o.TableId = t.Id
	WHERE
		o.Id = _OrderId
    ;
END$$

DELIMITER ;

USE `fastorder`;
DROP procedure IF EXISTS `GetOrderDetailByStoreId`;

DELIMITER $$
USE `fastorder`$$
CREATE PROCEDURE `GetOrderDetailByStoreId` (
	_StoreId int
)
BEGIN
	SELECT 
    od.OrderId,
    t.TableName,
    od.ProductName,
    od.Quantity,
    od.Price,
    o.DateCreate
	FROM
		orderdetail od
			JOIN
		`order` o ON od.OrderId = o.Id
			JOIN
		`table` t ON o.TableId = t.Id
			JOIN
		store s ON s.Id = t.StoreId
	WHERE
		s.Id = _StoreId
	ORDER BY o.Id DESC;
END$$

DELIMITER ;

USE `fastorder`;
DROP procedure IF EXISTS `GetProductById`;

DELIMITER $$
USE `fastorder`$$
CREATE PROCEDURE `GetProductById` (
	_ProductId int
)
BEGIN
	SELECT 
		`products`.`Id`,
		`StoreId`,
		`ImageId`,
		`ProductName`,
		`ProductPrice`,
		`TypeId`,
		CASE
			WHEN IsAvailable = 0 THEN FALSE
			ELSE TRUE
		END AS IsAvailable
	FROM
		`products`
	WHERE
		Id = _ProductId
        AND IsDeleted = 0
		AND IsAvailable = 1
	;
END$$

DELIMITER ;

USE `fastorder`;
DROP procedure IF EXISTS `GetAllProduct`;

DELIMITER $$
USE `fastorder`$$
CREATE PROCEDURE `GetAllProduct` (
	_Tablekey text
)
BEGIN
	SELECT 
		p.id,
		ty.Id AS TypeId,
		p.ProductName,
		ty.`Type`,
		t.TableName,
		s.StoreName,
		p.ProductPrice
	FROM
		`table` t
	JOIN store s ON t.storeid = s.id
	JOIN products p ON s.id = p.storeid
	JOIN `type` ty ON ty.id = p.typeid
	WHERE
		t.tablekey = _TableKey AND p.IsDeleted = 0
		;
END$$

DELIMITER ;

USE `fastorder`;
DROP procedure IF EXISTS `GetProductByType`;

DELIMITER $$
USE `fastorder`$$
CREATE PROCEDURE `GetProductByType` (
	_Tablekey text,
    _TypeId int
)
BEGIN
	SELECT *
	FROM (SELECT 
			p.id,
			ty.Id AS TypeId,
			p.ProductName,
			ty.`Type`,
			t.TableName,
			s.StoreName,
			p.ProductPrice,
			i.ImgKey
		FROM
			`table` t
		JOIN store s ON t.storeid = s.id
		JOIN products p ON s.id = p.storeid
		JOIN `type` ty ON ty.id = p.typeid
		JOIN `image` i ON i.Id = p.ImageId
		WHERE
				t.tablekey = _Tablekey AND p.IsDeleted = 0 AND p.IsAvailable = 1) a
	WHERE
		a.TypeId LIKE CONCAT('%', _TypeId , '%')
		;
END$$

DELIMITER ;

USE `fastorder`;
DROP procedure IF EXISTS `GetAllStore`;

DELIMITER $$
USE `fastorder`$$
CREATE PROCEDURE `GetAllStore` ()
BEGIN
	SELECT `Id`, `StoreKey`, `Location`,`StoreName`,`PhoneNumber`,
		`Province`,`UserId`,
		CASE WHEN IsDeleted = 0 THEN FALSE ELSE TRUE END AS IsDeleted
	FROM `store` WHERE IsDeleted=0
        ;
END$$

DELIMITER ;

USE `fastorder`;
DROP procedure IF EXISTS `UpdateStore`;

DELIMITER $$
USE `fastorder`$$
CREATE PROCEDURE `UpdateStore` (
	_StoreId int,
	_Location text,
    _PhoneNumber text,
    _StoreName text,
    _Province text
)
BEGIN
	UPDATE `fastorder`.`store`SET
		`Location` = _Location,
		`PhoneNumber` = _PhoneNumber,
		`StoreName` = _StoreName,
		`Province` = _Province
	WHERE `Id` = _StoreId
	;
END$$

DELIMITER ;

USE `fastorder`;
DROP procedure IF EXISTS `GetTableStatus`;

DELIMITER $$
USE `fastorder`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetTableStatus`(
	_TableKey text
)
BEGIN
	SELECT CASE WHEN t.IsAvailable = 0 THEN FALSE ELSE TRUE END AS `IsAvailable`
	FROM `table` t
	WHERE t.TableKey = _TableKey
	;
END$$

DELIMITER ;
USE `fastorder`;
DROP procedure IF EXISTS `UpdateTable`;

DELIMITER $$
USE `fastorder`$$
CREATE PROCEDURE `UpdateTable` (
	_TableId int,
    _TableName text,
    _IsAvailable text
)
BEGIN
	UPDATE `fastorder`.`table`
		SET `TableName`   = _TableName,
			`IsAvailable` = _IsAvailable
	WHERE `Id` = _TableId
        ;
END$$

DELIMITER ;

USE `fastorder`;
DROP procedure IF EXISTS `GetAllTableKey`;

DELIMITER $$
USE `fastorder`$$
CREATE PROCEDURE `GetAllTableKey` (
	_TableKey text
)
BEGIN
	SELECT t.Id AS TableId, s.Id AS StoreId, t.TableKey, t.TableName, s.StoreName
	FROM `table` t
		JOIN store s ON s.Id = t.StoreId
	WHERE t.TableKey = _TableKey
		;
END$$

DELIMITER ;

USE `fastorder`;
DROP procedure IF EXISTS `GetAllUser`;

DELIMITER $$
USE `fastorder`$$
CREATE PROCEDURE `GetAllUser` ()
BEGIN
	SELECT 
    u.Id,
    u.UserName,
    u.Fullname,
    u.Address,
    u.StoreId,
    u.RoleId,
    u.Password,
    s.StoreName,
    r.RoleType
	FROM
		user u,
		store s,
		role r
	WHERE
		u.StoreId = s.Id AND r.Id = u.RoleId
			AND u.IsDeleted = 0
        ;
END$$

DELIMITER ;

USE `fastorder`;
DROP procedure IF EXISTS `UpdateUser`;

DELIMITER $$
USE `fastorder`$$
CREATE PROCEDURE `UpdateUser` (
	_UserId int,
    _FullName text,
    _Address text
)
BEGIN
	UPDATE `fastorder`.`user`SET
		`Fullname` = _FullName,
		`Address` = _Address
	WHERE `Id` = _UserId
		;
END$$

DELIMITER ;

